### ISSUE TITLE
[Build] Build and release workflow 📦 

### ISSUE THREAD

**Issue by krfong916** [krfong916/swish-design#15]
# Tech Spec

We should make developed components as a package available on NPM for distribution and this repo for storybook development. Currently we publish this repo to npm, 🙅  no good.

## Tasks
- [x] create new branch for build and release flow
- [x] setup ./src as package to be published to npm excluding stories
- [x] lastly, automate the workflow

**Comment by krfong916** [comment]
Don't worry fellas, I'll take this issue.
