### ISSUE TITLE
[Component] Pin Input

### ISSUE THREAD

**Issue by krfong916** [krfong916/swish-design#19]
# Tech Spec

## UI
[Hi-Fi Prototype](https://www.figma.com/file/1pwkxyFOyWt521JubJWPze/Pin-Input?node-id=0%3A1)
[Study](https://docs.google.com/presentation/d/1yF3RI__DtnXXL7_Bl03MVn9NjySdNZ7dVsRRHq2ZzLk/edit?usp=sharing)

## UX
[User-Experience Spec](https://docs.google.com/document/d/1ZpnDrni95D0Ue9pPGSkollqZ8jS0YMvYg2Moxa2hUCo/edit?usp=sharing)

# Preview
- Lines may not be rendered properly in image, zoom in
![Pin-Input](https://user-images.githubusercontent.com/17156721/114085927-dd311680-9866-11eb-91e7-fbe50af81b30.png)

## Tasks

- [x] remove placeholder when there's a current focus (corner-case - using tab to move focus doesn't cause re-render. Focus is managed in state. If last box is unfilled and user hits tab, the box of origin will have no placeholder, placeholder presence is calculated at runtime obv)
- [x] allow copy paste
- [x] mask
- [x] left and right arrow keys
- [x] if value already present - focus on the input value/blur
- [x] standardize naming convention for styles
- [x] styling
- [x] size
- [x] variant: "outline" | "unstyled" | "filled" | "flushed"
- [x] separate hooks from styling etc. so ppl can have the functionality, and style however they like
- [x] forwardRef
- [x] previous tab/focus should not delete a character, only keep the highlight
